export const RECEIVE_CURRENT_WEATHER = 'RECEIVE_CURRENT_WEATHER'
export const RECEIVE_DAILY_WEATHER = 'RECEIVE_DAILY_WEATHER'
export const RECEIVE_FORECAST = 'RECEIVE_FORECAST'

export const REQUEST_WEATHER = 'REQUEST_WEATHER'

export const FETCH_WEATHER_FAILURE = 'FETCH_WEATHER_FAILURE'

export const FILTER_RANK_HIGH = 'FILTER_RANK_HIGH'
export const FILTER_NAME_HIGH = 'FILTER_NAME_HIGH'
export const FILTER_TEMPERATURE_HIGH = 'FILTER_TEMPERATURE_HIGH'
export const FILTER_WIND_HIGH = 'FILTER_WIND_HIGH'
export const FILTER_HUMIDITY_HIGH = 'FILTER_HUMIDITY_HIGH'
export const FILTER_PRESSURE_HIGH = 'FILTER_PRESSURE_HIGH'
export const FILTER_VISIBILITY_HIGH = 'FILTER_VISIBILITY_HIGH'
export const FILTER_BY_DEFINITION = 'FILTER_BY_DEFINITION'
export const SORT_BY = 'SORT_BY'

export const REQUEST_CITIES = 'REQUEST_CITIES'
export const RECEIVE_CITIES = 'RECEIVE_CITIES'
