// weather
export const RECEIVE_WEATHER_CURRENT = 'RECEIVE_WEATHER_CURRENT'
export const RECEIVE_WEATHER_DAILY = 'RECEIVE_WEATHER_DAILY'
export const RECEIVE_WEATHER_FORECAST = 'RECEIVE_WEATHER_FORECAST'
export const REQUEST_WEATHER = 'REQUEST_WEATHER'
export const FETCH_WEATHER_FAILURE = 'FETCH_WEATHER_FAILURE'

// filter
export const FILTER_RANK_HIGH = 'FILTER_RANK_HIGH'
export const FILTER_NAME_HIGH = 'FILTER_NAME_HIGH'
export const FILTER_TEMPERATURE_HIGH = 'FILTER_TEMPERATURE_HIGH'
export const FILTER_WEATHER_PARAMS = 'FILTER_WEATHER_PARAMS'

// cities
export const REQUEST_CITIES = 'REQUEST_CITIES'
export const RECEIVE_CITIES = 'RECEIVE_CITIES'

export const SET_PAGES = 'SET_PAGES'
